import { Inter } from "next/font/google";
import "./globals.css";
import Copyright from "@/components/Copyright";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Fake Store Proj",
  description: "Generated by create next app",
  author: "Collin Chamberlin"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Copyright sx={{ nt: 8, mb: 4 }} />
    </html>
  );
}
